# Generated by Django 3.1.5 on 2021-01-30 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0003_auto_20210130_0747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='samplestatushistory',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
