# Generated by Django 3.1.5 on 2021-01-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0004_auto_20210130_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='retry',
            field=models.IntegerField(default=0),
        ),
    ]
