# Generated by Django 3.1.5 on 2021-01-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('samples', '0005_auto_20210130_1319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='samplestatushistory',
            old_name='samples',
            new_name='sample',
        ),
    ]
